dist: trusty
sudo: required

install:
  - docker run --name buildkit --rm -d --privileged -p 1234:1234 tonistiigi/buildkit --addr tcp://0.0.0.0:1234
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234

env:
  global:
    - PLATFORMS="linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x,linux/ppc64le"
    - PREFER_BUILDCTL="1"

script:
  - make binaries validate-all && ./hack/cross

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: ./hack/release master tonistiigi/buildkit push
    on:
      repo: moby/buildkit
      branch: master
  - provider: script
    script: ./hack/release $TRAVIS_TAG tonistiigi/buildkit push
    on:
      repo: moby/buildkit
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]